name: Build and Publish Docker image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-push-amd64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract tag
        id: extract_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
          else
            echo "::set-output name=tag::latest"
          fi

      - name: Build and push Docker image (amd64)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            synthesis/mcp-server:latest-amd64
            synthesis/mcp-server:${{ steps.extract_tag.outputs.tag }}-amd64

  build-and-push-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract tag
        id: extract_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
          else
            echo "::set-output name=tag::latest"
          fi

      - name: Build and push Docker image (arm64)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            synthesis/mcp-server:latest-arm64
            synthesis/mcp-server:${{ steps.extract_tag.outputs.tag }}-arm64

  create-and-push-manifest:
    needs: [build-and-push-amd64, build-and-push-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract tag
        id: extract_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
          else
            echo "::set-output name=tag::latest"
          fi

      - name: Create and push multi-arch manifest (latest)
        run: |
          docker manifest create synthesis/mcp-server:latest \
            synthesis/mcp-server:latest-amd64 \
            synthesis/mcp-server:latest-arm64
          docker manifest push synthesis/mcp-server:latest

      - name: Create and push multi-arch manifest (tag)
        run: |
          docker manifest create synthesis/mcp-server:${{ steps.extract_tag.outputs.tag }} \
            synthesis/mcp-server:${{ steps.extract_tag.outputs.tag }}-amd64 \
            synthesis/mcp-server:${{ steps.extract_tag.outputs.tag }}-arm64
          docker manifest push synthesis/mcp-server:${{ steps.extract_tag.outputs.tag }}